version: '3'
services:
  oidc_kc:
    container_name: oidc
    image: jboss/keycloak
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./oidc/tls.crt:/etc/x509/https/tls.crt
      - ./oidc/tls.key:/etc/x509/https/tls.key
      - ./pgdata:/opt/jboss/keycloak/standalone/data
      - ./theme_uhn/themes/uhn:/opt/jboss/keycloak/themes/uhn
    environment:
      KEYCLOAK_USER: kcadmin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgresdb
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak

  postgresdb:
    container_name: postgresdb
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./oidc/setup_postgres.sh:/tmp/setup_postgres.sh
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

  ldap_mock:
    container_name: ldap
    image: osixia/openldap
    environment:
      LDAP_DOMAIN: example.org
      LDAP_ADMIN_PASSWORD: admin
    ports:
      - "3890:389"